services:
  # The Broker (The in-memory database for messages)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Web Application
  web:
    build: .
    command: uvicorn streaming_service.asgi:application --host 0.0.0.0 --port 8050
    volumes:
      - ./streaming_service:/app
    ports:
      - "8050:8050"
    env_file:
      - .env
    depends_on:
      - redis

  # The Celery Worker (runs tasks in the background)
  celery-worker:
    build: .
    command: celery -A streaming_service worker -l info
    volumes:
      - ./streaming_service:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web

  # The Celery Beat (The "clock" that triggers automatic tasks)
  celery-beat:
    build: .
    command: celery -A streaming_service beat -l info
    volumes:
      - ./streaming_service:/app
    env_file:
      - .env
    depends_on:
      - redis