# Generated by Django 6.0.2 on 2026-03-15 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('overview', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('vote_average', models.FloatField(default=0.0)),
                ('popularity', models.FloatField(default=0.0)),
                ('video_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=False)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_movies', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios que la tienen como favorita')),
            ],
            options={
                'ordering': ['-popularity', '-vote_average', 'title'],
                'indexes': [models.Index(fields=['title', 'release_date'], name='core_movie_title_bd84bb_idx')],
            },
        ),
    ]
