# Generated by Django 6.0.2 on 2026-03-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('profile_path', models.CharField(blank=True, max_length=255, null=True)),
                ('popularity', models.FloatField(blank=True, default=0.0)),
            ],
            options={
                'ordering': ['-popularity', 'name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movies', to='core.actor', verbose_name='Actores'),
        ),
    ]
