# Generated by Django 6.0.2 on 2026-03-23 00:21

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_movie_video_url'),
    ]

    operations = [
        VectorExtension(),
    ]
