# Generated by Django 6.0.2 on 2026-03-30 02:02

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260322_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
