# Generated by Django 6.0.2 on 2026-04-02 22:31

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movie_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='embedding_tokens',
            field=models.IntegerField(blank=True, default=0, help_text='Tokens spent on Gemini', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_movies', to=settings.AUTH_USER_MODEL, verbose_name='Users who have bookmarked it'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('preference_tokens', models.IntegerField(default=0, help_text='Tokens spent on Gemini')),
                ('has_completed_onboarding', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
