# Generated by Django 6.0.2 on 2026-04-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movie_director_movie_embedding_tokens_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ['-watched_at']},
        ),
    ]
