# Generated by Django 6.0.2 on 2026-04-12 19:34

import pgvector.django.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_watchhistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='core_movie_title_bd84bb_idx',
        ),
        migrations.AlterField(
            model_name='movie',
            name='embedding_tokens',
            field=models.IntegerField(default=0, help_text='Tokens consumidos en Gemini'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_movies', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios que la tienen como favorita'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='movie_embed_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
    ]
