# Generated by Django 6.0.2 on 2026-04-19 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_movie_director'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_style',
            field=models.CharField(choices=[('bottts', 'AI Robot'), ('identicon', 'Geometric Pattern'), ('pixel-art', 'Pixel Art'), ('shapes', 'Abstract Forms')], default='bottts', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='embedding_tokens',
            field=models.IntegerField(blank=True, default=0, help_text='Tokens spent on Gemini', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_movies', to=settings.AUTH_USER_MODEL, verbose_name='Users who have bookmarked it'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
