# Generated by Django 6.0.2 on 2026-04-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_avatar_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True, help_text='Runtime in minutes', null=True),
        ),
    ]
