# Generated by Django 6.0.2 on 2026-04-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_searchanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='fetch_and_vectorize_movies', max_length=255)),
                ('movies_processed', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('execution_time_seconds', models.FloatField(help_text='Total duration of the script')),
                ('status', models.CharField(default='Success', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pipeline Analytics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
