# Generated by Django 6.0.2 on 2026-04-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pipelineanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disliked_movies',
            field=models.ManyToManyField(blank=True, related_name='disliked_by', to='core.movie'),
        ),
    ]
